plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/omeratli/Desktop/esin anlas website"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]